### ISSUE TITLE
Running the contributed command:'GreetsnQuotes.greet' failed

### ISSUE THREAD

**Issue by alexcambose** [AkashGutha/vscode-greetings#1]
Please see the image below:
![](https://i.imgur.com/iSko5Fp.png)
This happens when I run `Greet or Quote` command.

**Comment by AkashGutha** [comment]
@alexcambose  This extension was written 2 years ago. I haven't upgraded it since then. The VSCode extension model has been updated and I might not have the time to look into this issue or upgrade the extension.

Thanks for reporting BTW! Cheers!

**Comment by alexcambose** [comment]
I opened a pull request [here](https://github.com/AkashGutha/vscode-greetings/pull/2)
